name = "yad"
license = "MIT"
licenselink = "https://github.com/celestialcrown7/celestialcrown7.github.io"
description = "ayo whatup my nigga"
homepage = "https://github.com/co1ncidence/hugo-theme-nuance"
tags = ["blog", "minimal", "monospace", "dark mode", "simple", "clean", "light", "responsive", "fast", "no-js", "no-tracking", "privacy"]
features = ["blog", "privacy", "responsive", "fast"]
min_version = "0.20"

[author]
  name = "'yad"
  homepage = "'yad.com"
