publishdir = ".."
baseURL = "https://celestialcrown7.github.io/"
languageCode = "en-us"
title = "Celestial Crown"
theme = "nuance"
paginate = 10

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Ayad Masud"

[params]
   author = "nuaNce"
   description = "Just a place where I rant and sometimes say something smart"
   subTitle = "Garfield Hates Monday And So Do I"
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   customCSS = ["css/style.css"]

[markup]
  [markup.highlight]
    pygmentsUseClasses=true
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[menu]

  [[menu.main]]
    name = "About /"
    identifier = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Posts /"
    identifier = "archive"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Vibe"
    identifier = "vibe"
    url = "/vibe/"
    weight = 4

[social]
  # github = "https://www.github.com/co1ncidence/"
  # discord = "https://discord.gg/TnJ4h5K"
  # reddit = "https://www.reddit.com/user/fps_co1ncidence"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
